version: '3.8'

services:
  sp:
    image: johannesjo/super-productivity:latest
    container_name: super-productivity
    restart: unless-stopped
    environment:
      - WEBDAV_BACKEND=http://webdav
    networks:
      - ha_addon

  webdav:
    image: hacdias/webdav:latest
    container_name: webdav
    restart: unless-stopped
    volumes:
      - ./webdav.yaml:/config.yml:ro
      - ./data:/data
    networks:
      - ha_addon

networks:
  ha_addon:
    driver: bridge
